version: '3.8'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/app
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - SPRING_DATASOURCE_URL=jdbc:postgressql://db:5432/eventdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"