spring:
  flyway:
    enabled: true
    url: jdbc:postgressql://localhost:5432/eventdb
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

  jpa:
    generate-ddl: true

